/* footer.js, one shared site footer, injected on public pages for consistent
   internal linking (SEO) + trust signals. Uses the design tokens from styles.css,
   so it adapts to light/dark automatically. Skips pages that already have a
   <footer> (e.g. the landing page has its own). */
(function () {
  if (document.querySelector('footer.app-footer') || document.querySelector('.home-footer')) return;

  var YEAR = new Date().getFullYear();
  var css = ''
    + '.app-footer{border-top:1px solid var(--border);margin-top:64px;padding:44px 20px 30px;color:var(--muted);font-size:13.5px;background:var(--bg-1);} '
    + '.app-footer-in{max-width:1180px;margin:0 auto;display:grid;grid-template-columns:1.5fr repeat(5, 1fr);gap:26px;} '
    + '@media(max-width:900px){.app-footer-in{grid-template-columns:1fr 1fr 1fr;gap:24px;}} '
    + '@media(max-width:560px){.app-footer-in{grid-template-columns:1fr 1fr;gap:20px;}} '
    + '.app-footer-brand{display:flex;align-items:center;gap:9px;font-weight:800;font-size:16px;color:var(--text);} '
    + '.app-footer-brand img{width:26px;height:26px;border-radius:7px;} '
    + '.app-footer-tag{margin-top:10px;line-height:1.55;max-width:280px;} '
    + '.app-footer-col-wide{grid-column:1 / -1;} '
    + '@media(min-width:901px){.app-footer-col-brand{grid-row:span 1;}} '
    + '.app-footer h4{font-size:12px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--text);margin:2px 0 12px;} '
    + '.app-footer a{display:block;color:var(--muted);padding:4px 0;transition:color .15s;line-height:1.35;} '
    + '.app-footer a:hover{color:var(--accent);} '
    + '.app-footer-seo{max-width:1180px;margin:26px auto 0;padding-top:20px;border-top:1px solid var(--border);} '
    + '.app-footer-seo h4{font-size:12px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--text);margin:0 0 10px;} '
    + '.app-footer-seo-links{display:flex;flex-wrap:wrap;gap:4px 0;} '
    + '.app-footer-seo-links a{color:var(--muted);font-size:12.5px;padding:3px 0;} '
    + '.app-footer-seo-links a:not(:last-child)::after{content:"·";margin:0 8px;color:var(--border);} '
    + '.app-footer-seo-links a:hover{color:var(--accent);} '
    + '.app-footer-bot{max-width:1180px;margin:26px auto 0;padding-top:20px;border-top:1px solid var(--border);display:flex;justify-content:space-between;gap:14px;flex-wrap:wrap;font-size:12.5px;} '
    + '.app-footer-bot a{display:inline;} ';
  var style = document.createElement('style');
  style.textContent = css;
  document.head.appendChild(style);

  var html = ''
    + '<div class="app-footer-in">'
    +   '<div class="app-footer-col-brand">'
    +     '<div class="app-footer-brand"><img src="/logo.jpeg" alt="Applio AI resume builder logo"> Applio</div>'
    +     '<div class="app-footer-tag">The free AI resume builder and ATS checker. Build an ATS-friendly resume, tailor it to any job description, generate a cover letter, and land more interviews.</div>'
    +   '</div>'
    +   '<div><h4>Resume Builder</h4>'
    +     '<a href="/resume-builder">AI Resume Builder</a>'
    +     '<a href="/resume-templates">Resume Templates</a>'
    +     '<a href="/tools/ai-resume-writer">AI Resume Writer</a>'
    +     '<a href="/resume-examples">Resume Examples</a>'
    +     '<a href="/editor">Build a Resume Free</a>'
    +     '<a href="/pricing">Pricing</a>'
    +   '</div>'
    +   '<div><h4>ATS & Cover Letters</h4>'
    +     '<a href="/ats-checker">Free ATS Checker</a>'
    +     '<a href="/tools/resume-scorer">Resume Scorer</a>'
    +     '<a href="/tools/resume-job-match">Resume Job Match</a>'
    +     '<a href="/cover-letter-generator">Cover Letter Generator</a>'
    +     '<a href="/cover-letter-templates">Cover Letter Templates</a>'
    +     '<a href="/cover-letter-examples">Cover Letter Examples</a>'
    +   '</div>'
    +   '<div><h4>Free Tools</h4>'
    +     '<a href="/tools">All Free Resume Tools</a>'
    +     '<a href="/tools/resume-summary-generator">Resume Summary Generator</a>'
    +     '<a href="/tools/resume-bullet-generator">Bullet Point Generator</a>'
    +     '<a href="/tools/resume-skills-generator">Skills Generator</a>'
    +     '<a href="/tools/resume-proofreader">Resume Proofreader</a>'
    +     '<a href="/salary">Salary Calculator</a>'
    +   '</div>'
    +   '<div><h4>Learn</h4>'
    +     '<a href="/guides">Resume Guides</a>'
    +     '<a href="/guides/what-is-an-ats">What Is an ATS?</a>'
    +     '<a href="/guides/how-to-pass-ats">How to Pass the ATS</a>'
    +     '<a href="/guides/how-to-write-a-resume">How to Write a Resume</a>'
    +     '<a href="/interview-preparation">Interview Prep</a>'
    +     '<a href="/students">Students: Free Premium</a>'
    +   '</div>'
    +   '<div><h4>Compare</h4>'
    +     '<a href="/compare">Compare Resume Builders</a>'
    +     '<a href="/zety-alternative">Zety Alternative</a>'
    +     '<a href="/rezi-alternative">Rezi Alternative</a>'
    +     '<a href="/teal-alternative">Teal Alternative</a>'
    +     '<a href="/resume-io-alternative">Resume.io Alternative</a>'
    +     '<a href="/jobscan-alternative">Jobscan Alternative</a>'
    +   '</div>'
    + '</div>'
    + '<div class="app-footer-seo">'
    +   '<h4>Popular resume examples</h4>'
    +   '<div class="app-footer-seo-links">'
    +     '<a href="/resume-examples/software-engineer">Software Engineer</a>'
    +     '<a href="/resume-examples/registered-nurse">Registered Nurse</a>'
    +     '<a href="/resume-examples/project-manager">Project Manager</a>'
    +     '<a href="/resume-examples/data-analyst">Data Analyst</a>'
    +     '<a href="/resume-examples/accountant">Accountant</a>'
    +     '<a href="/resume-examples/teacher">Teacher</a>'
    +     '<a href="/resume-examples/marketing-manager">Marketing Manager</a>'
    +     '<a href="/resume-examples/customer-service-representative">Customer Service</a>'
    +     '<a href="/resume-examples/sales-representative">Sales Representative</a>'
    +     '<a href="/resume-examples/front-end-developer">Front-End Developer</a>'
    +     '<a href="/resume-examples/product-manager">Product Manager</a>'
    +     '<a href="/resume-examples/graphic-designer">Graphic Designer</a>'
    +     '<a href="/resume-examples/business-analyst">Business Analyst</a>'
    +     '<a href="/resume-examples/nurse-practitioner">Nurse Practitioner</a>'
    +     '<a href="/resume-examples">All 138 resume examples →</a>'
    +   '</div>'
    + '</div>'
    + '<div class="app-footer-seo">'
    +   '<h4>Beat the ATS by system</h4>'
    +   '<div class="app-footer-seo-links">'
    +     '<a href="/guides/workday-ats">Workday ATS</a>'
    +     '<a href="/guides/greenhouse-ats">Greenhouse ATS</a>'
    +     '<a href="/guides/lever-ats">Lever ATS</a>'
    +     '<a href="/guides/icims-ats">iCIMS ATS</a>'
    +     '<a href="/guides/taleo-ats">Taleo ATS</a>'
    +     '<a href="/guides/ashby-ats">Ashby ATS</a>'
    +     '<a href="/guides/resume-action-verbs">Resume Action Verbs</a>'
    +     '<a href="/guides/best-resume-format">Best Resume Format</a>'
    +     '<a href="/guides/how-to-tailor-resume-to-job">Tailor Resume to a Job</a>'
    +     '<a href="/privacy">Privacy</a>'
    +     '<a href="/terms">Terms</a>'
    +     '<a href="/email-preferences">Email preferences</a>'
    +   '</div>'
    + '</div>'
    + '<div class="app-footer-bot">'
    +   '<span>© ' + YEAR + ' Applio · Built for job seekers everywhere</span>'
    +   '<span style="display:inline-flex;align-items:center;gap:7px;"><svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="opacity:.8;"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>Data encrypted · PBKDF2-hashed passwords · Never sold</span>'
    + '</div>';

  var footer = document.createElement('footer');
  footer.className = 'app-footer';
  footer.innerHTML = html;
  document.body.appendChild(footer);
})();
