/* build-rb.js — writes the resume-builder hub + audience landing pages. */
const fs = require('fs');
const path = require('path');
const { page } = require('./gen-rb.js');
const ROOT = path.join(__dirname, '..');

const RB_PARENT_NAV = '<a href="/resume-builder">Resume Builder</a> › ';
const RB_PARENT_LD = [{ name: 'Resume Builder', url: 'https://appliohq.com/resume-builder' }];
const relHub = { label: 'Free Resume Builder (all templates)', href: '/resume-builder' };
const relExamples = { label: 'Resume examples by job title', href: '/resume-examples' };

// ---------------- HUB ----------------
const hub = {
  slug: 'resume-builder',
  title: 'Free Resume Builder — Build an ATS-Ready Resume | Applio',
  ogTitle: 'Free Resume Builder',
  metaDescription: 'Free online resume builder. Pick from 18 recruiter-tested templates, import your old resume, and export a clean, ATS-ready PDF. No credit card, no watermark.',
  h1: 'Free Resume Builder',
  crumbNav: '',
  crumbParent: [],
  answer: 'Applio is a free online resume builder that helps you create an ATS-ready resume in minutes. Pick a recruiter-tested template, import your existing resume or type it in, and export a clean PDF — no credit card and no watermark on the free plan.',
  sections: [
    { h2: 'How the resume builder works', bodyHtml: '<ol><li><strong>Start from a template or import.</strong> Choose one of 18 ATS-friendly designs, or upload an existing PDF/DOCX and let Applio parse it into editable sections.</li><li><strong>Fill in your sections.</strong> Add your experience, education, skills, and projects. A live preview shows exactly what recruiters and the PDF will see.</li><li><strong>Optimize and export.</strong> Check your ATS score against a job, tighten your bullets, then download a clean PDF (or HTML/TXT) ready to submit.</li></ol>' },
    { h2: 'What you get for free', bodyHtml: '<ul><li>All 18 professional, fully customizable templates (fonts, colors, spacing, section order).</li><li>AI resume import from PDF, DOCX, or TXT so you don\'t retype anything.</li><li>A built-in job-application tracker and AI interview prep.</li><li>A live preview that matches the exported PDF exactly — no surprises.</li><li>Clean, single-column, ATS-safe formatting by default.</li></ul>' },
    { h2: 'Built for your situation', bodyHtml: 'Every field is a little different — here are resume builders tuned to specific job seekers, with advice and examples for each:<div class="rb-grid"><a href="/resume-builder-for-students">Resume builder for students</a><a href="/resume-builder-for-high-school-students">Resume builder for high school students</a><a href="/resume-builder-for-internships">Resume builder for internships</a><a href="/resume-builder-for-software-engineers">Resume builder for software engineers</a><a href="/resume-builder-for-nurses">Resume builder for nurses</a><a href="/resume-builder-for-finance-jobs">Resume builder for finance jobs</a><a href="/resume-builder-for-teachers">Resume builder for teachers</a><a href="/resume-builder-for-career-changers">Resume builder for career changers</a><a href="/resume-builder-for-no-experience">Resume builder for no experience</a><a href="/resume-builder-for-project-managers">Resume builder for project managers</a></div>' },
    { h2: 'Templates, examples, and guides', bodyHtml: '<ul><li>Browse all <a href="/resume-templates">resume templates</a> and switch between them anytime without retyping.</li><li>See real <a href="/resume-examples">resume examples by job title</a> for inspiration and structure.</li><li>Check your resume with the free <a href="/ats-checker">ATS resume checker</a> before you apply.</li><li>Learn the fundamentals in our <a href="/guides">resume &amp; job-search guides</a>.</li></ul>' }
  ],
  faq: [
    { q: 'Is the resume builder really free?', a: 'Yes. You can build a resume, use all 18 templates, import an existing resume, and download 10 PDFs per month for free — no credit card required. Premium unlocks unlimited downloads and the AI writing tools.' },
    { q: 'Are the resumes ATS-friendly?', a: 'Yes. Every template uses a single-column, standard-heading layout with real selectable text, which is what applicant tracking systems parse most reliably. You can also score your resume against a job with the built-in ATS checker.' },
    { q: 'Can I import my existing resume?', a: 'Yes. Upload a PDF, DOCX, or TXT and Applio extracts your details into editable sections, so you don\'t have to retype anything.' },
    { q: 'Will there be a watermark on my resume?', a: 'No. Exported resumes have no Applio watermark on any plan.' }
  ],
  related: [relExamples, { label: 'Free ATS resume checker', href: '/ats-checker' }, { label: 'Resume templates', href: '/resume-templates' }, { label: 'Resume & job-search guides', href: '/guides' }],
  finalTitle: 'Ready to build your resume?',
  finalSub: 'Free to start, no credit card, no watermark. Export a recruiter-ready PDF in minutes.'
};

// ---------------- AUDIENCE PAGES (content drafted per-audience) ----------------
const audiences = [
  {
    slug: 'resume-builder-for-students', h1: 'Resume Builder for College Students',
    title: 'Resume Builder for Students: Free Guide & Tips',
    metaDescription: 'A resume builder for students with no work experience. Learn to lead with education, projects, and campus activities, plus real bullet examples that get interviews.',
    answer: 'A student resume flips the usual formula: with little or no work history, you lead with education, projects, and campus involvement instead of jobs. Focus on showing skills through coursework, activities, and measurable results so employers see potential, not just experience.',
    sections: [
      { h2: 'Why a student resume is different', bodyHtml: '&lt;p&gt;Most resume advice assumes years of full-time jobs to list. As a college student, you likely have none of that yet, and that\'s completely normal. Instead of a long work history, your strongest assets are your education, class projects, leadership in clubs, and any part-time or campus work you\'ve done. Employers hiring students and new grads expect this and want to see potential, drive, and transferable skills.&lt;/p&gt;&lt;p&gt;That means the layout shifts: your Education section moves to the top, and you fill the page with projects, coursework, activities, and skills rather than job titles. One page is plenty. The goal is to prove you can learn fast, take initiative, and deliver results, even if you gained those abilities in a classroom or a student org rather than a cubicle.&lt;/p&gt;' },
      { h2: 'What to put on a student resume', bodyHtml: '&lt;ul&gt;&lt;li&gt;Your degree, major, expected graduation date, and school, so recruiters immediately see where you are in your studies.&lt;/li&gt;&lt;li&gt;GPA if it\'s 3.5 or above, because a strong GPA signals discipline when you lack a work track record.&lt;/li&gt;&lt;li&gt;Relevant coursework tied to the role, which shows you have foundational knowledge even without job experience.&lt;/li&gt;&lt;li&gt;Academic or personal projects with a one-line description of what you built or analyzed and the outcome.&lt;/li&gt;&lt;li&gt;Leadership roles in clubs, teams, or student government, since managing people and events proves real responsibility.&lt;/li&gt;&lt;li&gt;Part-time, campus, or summer jobs of any kind, because they demonstrate reliability, time management, and work ethic.&lt;/li&gt;&lt;li&gt;Volunteer work and community involvement, which fill out your experience and show initiative and character.&lt;/li&gt;&lt;li&gt;Technical, software, and language skills listed concretely, so recruiters can match you to specific tools and requirements.&lt;/li&gt;&lt;/ul&gt;' },
      { h2: 'Student resume bullet examples', bodyHtml: '&lt;ul&gt;&lt;li&gt;Led a 5-person team on a semester-long marketing project, delivering a campaign proposal that scored in the &lt;strong&gt;top 10%&lt;/strong&gt; of the class.&lt;/li&gt;&lt;li&gt;Managed the front desk at a campus recreation center, processing over &lt;strong&gt;80 member check-ins per shift&lt;/strong&gt; while resolving scheduling conflicts.&lt;/li&gt;&lt;li&gt;Built a Python program to analyze a public dataset of &lt;strong&gt;10,000+ records&lt;/strong&gt;, producing visualizations for a final course presentation.&lt;/li&gt;&lt;/ul&gt;' }
    ],
    faq: [
      { q: 'What if I have no work experience at all?', a: 'That\'s fine, and very common. Lead with your education, class projects, coursework, clubs, and volunteer work; these show skills and initiative just as effectively as a job.' },
      { q: 'Should I include my GPA?', a: 'Include it if it\'s 3.5 or higher, or if a specific employer asks for it. If it\'s lower, leave it off and let your projects and activities do the talking.' },
      { q: 'How long should a college student\'s resume be?', a: 'One page. Recruiters spend only seconds per resume, so keep it focused on your most relevant education, projects, and skills rather than padding it out.' }
    ],
    related: [relHub, relExamples, { label: 'How to write a resume summary', href: '/guides/how-to-write-resume-summary' }, { label: 'How to list skills on a resume', href: '/guides/how-to-list-skills-on-a-resume' }]
  },
  {
    slug: 'resume-builder-for-high-school-students', h1: 'Resume Builder for High School Students',
    title: 'Resume Builder for High School Students: Free Guide',
    metaDescription: 'Build your first resume with no work experience. See what to include, real bullet examples, and a checklist made for high school students applying to jobs and college.',
    answer: 'As a high school student, your first resume is built from what you\'ve already done: classes, clubs, sports, volunteering, and skills, not full-time jobs. Keep it to one honest page and use it for part-time work, college and scholarship applications, and summer programs.',
    sections: [
      { h2: 'Why a high school resume is different', bodyHtml: '&lt;p&gt;Most high school students don\'t have formal work history yet, and that\'s completely normal. Instead of past jobs, your resume showcases what you\'ve done in school, activities, sports, volunteering, and the skills you\'ve picked up along the way.&lt;/p&gt;&lt;p&gt;Keep it honest and to one page. You\'ll use the same core resume for part-time jobs, college and scholarship applications, and summer programs, tweaking it slightly for each.&lt;/p&gt;' },
      { h2: 'What to put on a high school resume', bodyHtml: '&lt;ul&gt;&lt;li&gt;&lt;strong&gt;Contact info:&lt;/strong&gt; your name, phone, and a professional email so employers and programs can actually reach you.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Objective (1 line):&lt;/strong&gt; what you\'re applying for, so the reader instantly knows your goal.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Education:&lt;/strong&gt; your school, expected graduation year, and GPA if it\'s strong (roughly 3.5+), since this is your main credential right now.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Relevant coursework:&lt;/strong&gt; AP, honors, or classes tied to the job or major, to show you have related knowledge.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Extracurriculars and sports:&lt;/strong&gt; clubs, teams, and any leadership roles, because they prove commitment and teamwork.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Volunteer work:&lt;/strong&gt; service hours and causes, which show responsibility and initiative outside of class.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Jobs and informal work:&lt;/strong&gt; babysitting, tutoring, lawn care, or a first part-time job, to demonstrate real reliability.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Awards and skills:&lt;/strong&gt; honor roll, competitions, languages, and tech tools (Excel, Canva, coding) that set you apart.&lt;/li&gt;&lt;/ul&gt;' },
      { h2: 'High school resume bullet examples', bodyHtml: '&lt;ul&gt;&lt;li&gt;Tutored &lt;strong&gt;5&lt;/strong&gt; middle school students in algebra weekly, helping two raise their grades by a full letter.&lt;/li&gt;&lt;li&gt;Organized a school food drive that collected over &lt;strong&gt;300&lt;/strong&gt; canned items for a local shelter.&lt;/li&gt;&lt;li&gt;Balanced varsity soccer and a part-time job at &lt;strong&gt;15&lt;/strong&gt; hours per week while maintaining a 3.7 GPA.&lt;/li&gt;&lt;/ul&gt;' }
    ],
    faq: [
      { q: 'Do I need a resume in high school?', a: 'Yes, if you\'re applying for part-time jobs, internships, competitive summer programs, or scholarships. Many college applications also let you attach one to highlight activities and awards.' },
      { q: 'What if I have no work experience?', a: 'That\'s expected, and employers know it. Fill your resume with school achievements, clubs, sports, volunteering, and informal work like babysitting or tutoring, all of which show reliability and skills.' },
      { q: 'How long should a high school resume be?', a: 'One page, always. At this stage you don\'t have enough experience to justify more, and a tight, focused page is easier for a busy employer or admissions reader to scan.' }
    ],
    related: [relHub, { label: 'The best resume format', href: '/guides/best-resume-format' }, { label: '150+ resume action verbs', href: '/guides/resume-action-verbs' }, relExamples]
  },
  {
    slug: 'resume-builder-for-internships', h1: 'Resume Builder for Internships',
    title: 'Resume Builder for Internships: Land Your First Role',
    metaDescription: 'A resume builder for internships built for students with little experience. Learn what to include, see quantified bullet examples, and tailor to each posting.',
    answer: 'An internship resume is a one-page document that sells your potential over your experience. Because employers know you\'re early in your career, lead with education, relevant coursework, class projects, and skills from the job posting rather than years of work history.',
    sections: [
      { h2: 'Why an internship resume is different', bodyHtml: '&lt;p&gt;Internship recruiters already expect you to have limited work experience, so they screen for potential instead of a long track record. They scan for relevant coursework, class or personal projects, campus involvement, and how closely your resume mirrors the specific internship posting.&lt;/p&gt;&lt;p&gt;Keep it to one page and echo the exact keywords from the job description. Many employers filter with applicant tracking systems, so a resume tailored to each posting beats one generic version sent everywhere.&lt;/p&gt;' },
      { h2: 'What to put on an internship resume', bodyHtml: '&lt;ul&gt;&lt;li&gt;&lt;strong&gt;A short summary aimed at the role&lt;/strong&gt; — two lines naming the internship and what you bring, so recruiters instantly see a fit.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Education with expected graduation date&lt;/strong&gt; — your major, school, and grad date matter most when work history is thin; add GPA if it\'s 3.5 or above.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Relevant coursework and projects&lt;/strong&gt; — these stand in for job experience and prove you can already do parts of the work.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Transferable skills from any job&lt;/strong&gt; — a retail or campus job shows reliability, communication, and time management that employers value.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Campus involvement and leadership&lt;/strong&gt; — clubs, teams, and volunteer roles demonstrate initiative and teamwork outside class.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Technical and tool skills&lt;/strong&gt; — list languages, software, and certifications so your resume matches keyword filters.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Keywords from each posting&lt;/strong&gt; — mirror the skills and terms the listing uses to pass ATS screens and signal a tailored application.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;A clean one-page format&lt;/strong&gt; — consistent fonts and clear headings keep a busy recruiter focused on your strengths.&lt;/li&gt;&lt;/ul&gt;' },
      { h2: 'Internship resume bullet examples', bodyHtml: '&lt;ul&gt;&lt;li&gt;Built a personal finance web app in a semester project, writing &lt;strong&gt;1,200+ lines of Python&lt;/strong&gt; and demoing it to a class of 40.&lt;/li&gt;&lt;li&gt;Trained and scheduled &lt;strong&gt;6 new part-time hires&lt;/strong&gt; while working weekends at a campus coffee shop, cutting onboarding time in half.&lt;/li&gt;&lt;li&gt;Coordinated a club fundraiser that drew &lt;strong&gt;150 attendees&lt;/strong&gt; and raised &lt;strong&gt;$2,300&lt;/strong&gt; for a local nonprofit.&lt;/li&gt;&lt;/ul&gt;' }
    ],
    faq: [
      { q: 'How do I write an internship resume with no work experience?', a: 'Lead with education, relevant coursework, and class or personal projects, then add campus involvement and any skills. Recruiters expect limited experience for internships, so focus on demonstrating potential and effort.' },
      { q: 'Should an internship resume include a GPA?', a: 'Include your GPA if it\'s roughly 3.5 or higher, or if the posting requests it. If it\'s lower, leave it off and let coursework, projects, and skills carry your application.' },
      { q: 'How long should an internship resume be?', a: 'One page. As a student or early-career applicant you rarely need more, and a tight single page is easier for recruiters to scan quickly.' }
    ],
    related: [relHub, { label: 'How to tailor your resume to a job', href: '/guides/how-to-tailor-resume-to-job' }, { label: 'How to write a resume summary', href: '/guides/how-to-write-resume-summary' }, relExamples]
  },
  {
    slug: 'resume-builder-for-software-engineers', h1: 'Resume Builder for Software Engineers',
    title: 'Resume Builder for Software Engineers | Land Interviews',
    metaDescription: 'A resume builder for software engineers that beats ATS filters: match the job\'s tech stack, quantify impact, and showcase GitHub, projects, and real system scale.',
    answer: 'A great software engineer resume proves impact with numbers, not adjectives. It mirrors the job description\'s exact tech stack for ATS keyword matching, quantifies what you shipped (latency, scale, cost, users), and links to real code. Keep it to one page unless you\'re senior.',
    sections: [
      { h2: 'Why a software engineer resume is different', bodyHtml: '&lt;p&gt;Engineering resumes are read twice: first by an ATS scanning for exact tech-stack keywords, then by a recruiter or hiring engineer who skims in seconds. If the job asks for Go, Kubernetes, and PostgreSQL, those exact terms need to appear — synonyms and vague phrasing get filtered out before a human ever sees them.&lt;/p&gt;&lt;p&gt;What separates strong resumes is proof. Hiring managers want quantified impact — latency cut, requests per second handled, dollars saved, users served — not a list of responsibilities. A linked GitHub, portfolio, or shipped project carries more weight than any "passionate problem-solver" line, and you should keep it to one page until you\'re senior or staff-level.&lt;/p&gt;' },
      { h2: 'What to put on a software engineer resume', bodyHtml: '&lt;ul&gt;&lt;li&gt;&lt;strong&gt;A Technical Skills section mirroring the JD\'s stack&lt;/strong&gt; — list the languages, frameworks, cloud, and tools the posting names, because that\'s what the ATS keyword-matches against.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Quantified impact bullets&lt;/strong&gt; — lead with the result (latency, throughput, cost, users) so reviewers see outcomes, not just tasks.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Notable projects with live links&lt;/strong&gt; — a working demo or repo lets an engineer verify your skill in one click instead of taking your word.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;System scale and scope&lt;/strong&gt; — note traffic, data volume, or team size (e.g., "serving 2M daily requests") so seniority reads clearly.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Open-source and GitHub&lt;/strong&gt; — real contributions and a green commit history signal you write and ship code, not just describe it.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Relevant CS education or equivalent&lt;/strong&gt; — degree, bootcamp, or notable certs; keep it brief and move it below experience once you have 2+ years.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Cut the soft-skill fluff&lt;/strong&gt; — "team player" and "detail-oriented" waste space; let quantified results imply those traits instead.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;ATS-parseable formatting&lt;/strong&gt; — single column, standard fonts, no tables or graphics, because multi-column PDFs often get scrambled on parse.&lt;/li&gt;&lt;/ul&gt;' },
      { h2: 'Software engineer resume bullet examples', bodyHtml: '&lt;ul&gt;&lt;li&gt;Rearchitected the checkout API in &lt;strong&gt;Go&lt;/strong&gt;, cutting p99 latency &lt;strong&gt;from 800ms to 210ms&lt;/strong&gt; and reducing timeout errors by 70%.&lt;/li&gt;&lt;li&gt;Built a caching layer with &lt;strong&gt;Redis&lt;/strong&gt; that scaled the search service to &lt;strong&gt;2M requests/day&lt;/strong&gt; while cutting database load 60%.&lt;/li&gt;&lt;li&gt;Migrated batch jobs to &lt;strong&gt;AWS Lambda&lt;/strong&gt;, lowering monthly compute spend &lt;strong&gt;by $18K&lt;/strong&gt; and eliminating on-call pages for the pipeline.&lt;/li&gt;&lt;/ul&gt;' }
    ],
    faq: [
      { q: 'How long should a software engineer resume be?', a: 'One page for new grads through mid-level engineers. Only go to two pages at senior, staff, or principal level where the breadth of scope genuinely warrants it.' },
      { q: 'Should I list every programming language I know?', a: 'No — list the languages relevant to the role and be honest about proficiency. Padding the skills section with tools you\'ve touched once dilutes the keywords that matter and invites interview questions you can\'t answer.' },
      { q: 'Do I need a GitHub or portfolio link on my resume?', a: 'It helps a lot, especially for new grads and self-taught engineers, since it lets reviewers verify your work directly. Link it only if the repos are clean and show real projects, not empty or abandoned ones.' }
    ],
    related: [relHub, { label: 'Software Engineer resume example', href: '/resume-examples/software-engineer' }, { label: 'How to pass the ATS', href: '/guides/how-to-pass-ats' }, { label: 'How to list skills on a resume', href: '/guides/how-to-list-skills-on-a-resume' }]
  },
  {
    slug: 'resume-builder-for-nurses', h1: 'Resume Builder for Nurses',
    title: 'Resume Builder for Nurses | RN Resume Templates',
    metaDescription: 'Build a nursing resume that passes hospital ATS screening. Highlight your RN license, certifications, clinical specialty, and EHR skills. Free templates for nurses.',
    answer: 'A nursing resume must lead with your active RN license, certifications, and clinical specialty because hospital recruiters and ATS software screen for exact credentials before a human ever reads it. Applio structures each of these fields so charge nurses and recruiters can verify your qualifications in seconds.',
    sections: [
      { h2: 'Why a nursing resume is different', bodyHtml: '&lt;p&gt;Unlike most resumes, a nursing resume is screened first for hard credentials: an active, unencumbered RN license, current certifications, and specialty experience tied to a specific unit. Applicant tracking systems used by hospital networks parse for exact terms — "BSN," "CCRN," "Epic," "ICU" — and rank you out if they are missing or buried.&lt;/p&gt;&lt;p&gt;Recruiters also read for patient acuity, unit type, and charting systems because a Med-Surg nurse and an ED nurse are not interchangeable. Your resume has to prove the right clinical fit, not just years of experience, so credentials and specialty belong at the top where both software and a hiring manager can find them fast.&lt;/p&gt;' },
      { h2: 'What to put on a nursing resume', bodyHtml: '&lt;ul&gt;&lt;li&gt;Your active RN license with the state and license number format (e.g., "RN, California, License #123456") so employers can verify it immediately via Nursys.&lt;/li&gt;&lt;li&gt;Current certifications — BLS, ACLS, PALS, and specialty credentials like CCRN, CEN, or OCN — because many units legally require them before you can work the floor.&lt;/li&gt;&lt;li&gt;Your clinical specialty and unit experience (ICU, ER, Med-Surg, L&amp;D, PACU) since recruiters hire for a specific department, not general nursing.&lt;/li&gt;&lt;li&gt;EHR and charting systems you know, such as Epic, Cerner, or Meditech, because charting proficiency reduces orientation time and is a frequent ATS keyword.&lt;/li&gt;&lt;li&gt;Typical patient load or nurse-to-patient ratios you managed, which signals the acuity level and pace you can handle.&lt;/li&gt;&lt;li&gt;Degree and licensure path (ADN vs. BSN) plus relevant clinical rotations, especially for new grads with limited paid experience.&lt;/li&gt;&lt;li&gt;Professional memberships and affiliations like the ANA or a specialty organization (AACN, ENA) to show engagement with your field.&lt;/li&gt;&lt;li&gt;Hard nursing skills — IV insertion, ventilator management, wound care, medication administration — mapped to the job posting\'s requirements.&lt;/li&gt;&lt;/ul&gt;' },
      { h2: 'Nursing resume bullet examples', bodyHtml: '&lt;ul&gt;&lt;li&gt;Managed a &lt;strong&gt;1:2 patient ratio&lt;/strong&gt; in a 24-bed surgical ICU, monitoring post-op and ventilated patients while maintaining zero central-line infections over 18 months.&lt;/li&gt;&lt;li&gt;Precepted &lt;strong&gt;12 new-graduate nurses&lt;/strong&gt; through unit orientation, contributing to a first-year retention rate above the department average.&lt;/li&gt;&lt;li&gt;Implemented a bedside shift-report protocol that helped raise unit &lt;strong&gt;HCAHPS communication scores by 15%&lt;/strong&gt; across two quarters.&lt;/li&gt;&lt;/ul&gt;' }
    ],
    faq: [
      { q: 'How do I list my RN license on a resume?', a: 'List it prominently near the top with your credential, issuing state, and license number, for example "RN, Texas, License #123456," along with the expiration date. This lets employers verify you through Nursys before scheduling an interview.' },
      { q: 'Should a new grad nurse resume include clinical rotations?', a: 'Yes. New graduates should list clinical rotations with the setting, unit type, and hours completed, since these stand in for paid experience and show which specialties you have hands-on exposure to.' },
      { q: 'Do I need a different resume for each nursing specialty?', a: 'You should tailor it. Lead with the certifications, EHR systems, and unit experience that match the specific posting, because ATS software and charge nurses screen for specialty-specific keywords rather than general nursing experience.' }
    ],
    related: [relHub, { label: 'Registered Nurse resume example', href: '/resume-examples/registered-nurse' }, { label: 'How to pass the ATS', href: '/guides/how-to-pass-ats' }, { label: 'How to list skills on a resume', href: '/guides/how-to-list-skills-on-a-resume' }]
  },
  {
    slug: 'resume-builder-for-finance-jobs', h1: 'Resume Builder for Finance Jobs',
    title: 'Resume Builder for Finance Jobs | Analyst & IB Tips',
    metaDescription: 'A resume builder for finance jobs that helps analysts, IB, FP&A, and corporate finance pros quantify impact, show technical skills, and land interviews.',
    answer: 'A finance resume must lead with quantified, dollar-denominated impact and prove technical fluency in Excel, financial modeling, and tools like Bloomberg or SQL. Recruiters scan for certifications (CFA, CPA), a strong GPA, and clean, one-page formatting that signals precision.',
    sections: [
      { h2: 'Why a finance resume is different', bodyHtml: '&lt;p&gt;Finance recruiters and hiring managers read resumes like they read financials: they want numbers. Generic bullets like "managed reporting process" get skipped, while quantified, dollar-denominated impact ($ managed, saved, or returned; variance reduced; basis points) signals you think in terms of value. Technical fluency in Excel, financial modeling, SQL, Bloomberg, and ERP systems is table stakes, not a bonus.&lt;/p&gt;&lt;p&gt;Formatting matters more than in most fields. A conservative, clean, one-page layout with zero typos signals the attention to accuracy the job demands. Credentials also carry weight: certifications like the CFA, CPA, or Series 7 (or clear progress toward them) and a strong GPA are expected on analyst and early-career resumes.&lt;/p&gt;' },
      { h2: 'What to put on a finance resume', bodyHtml: '&lt;ul&gt;&lt;li&gt;&lt;strong&gt;Quantified, dollar-denominated impact&lt;/strong&gt; — assets/budgets managed, costs saved, variance reduced, or returns generated; finance is measured in dollars, so your resume should be too.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Technical skills&lt;/strong&gt; — Excel (advanced functions, pivot tables), financial modeling/DCF/LBO, SQL, Bloomberg, Capital IQ, and ERP systems (SAP, Oracle, NetSuite); these are hard filters recruiters screen for.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Certifications and progress&lt;/strong&gt; — CFA (and level passed), CPA, Series 7/63, or FMVA; listing exams in progress shows commitment even before completion.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Relevant coursework and GPA&lt;/strong&gt; — include GPA if 3.5+ and coursework like corporate finance, econometrics, or accounting for early-career roles.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Deal or project experience&lt;/strong&gt; — transactions, valuations, models built, or audits led, with your specific role and the deal size; specifics prove you did the work.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Demonstrated accuracy&lt;/strong&gt; — reconciliations, controls, or audit findings; finance rewards people who don\'t make errors, so show it.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Conservative one-page format&lt;/strong&gt; — reverse-chronological, clean fonts, no graphics; anything flashy reads as a red flag in traditional finance.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Keywords from the job description&lt;/strong&gt; — mirror the exact tools and skills listed so you clear applicant tracking systems and recruiter scans.&lt;/li&gt;&lt;/ul&gt;' },
      { h2: 'Finance resume bullet examples', bodyHtml: '&lt;ul&gt;&lt;li&gt;Built a three-statement DCF model that supported a &lt;strong&gt;$45M acquisition&lt;/strong&gt;, identifying $6M in synergy upside that shaped the final bid.&lt;/li&gt;&lt;li&gt;Automated monthly variance reporting in Excel and SQL, cutting close time from &lt;strong&gt;5 days to 8 hours&lt;/strong&gt; and eliminating manual reconciliation errors.&lt;/li&gt;&lt;li&gt;Managed a &lt;strong&gt;$120M fixed-income portfolio&lt;/strong&gt;, outperforming the benchmark by 35 basis points over 18 months through duration positioning.&lt;/li&gt;&lt;/ul&gt;' }
    ],
    faq: [
      { q: 'Should I put my GPA on a finance resume?', a: 'Yes, if it\'s 3.5 or higher, especially for internships and entry-level analyst roles where GPA is a common screening filter. Drop it once you have several years of relevant experience.' },
      { q: 'Do I need the CFA to list it on my resume?', a: 'No. You can and should list "CFA Level I Candidate" or the level you\'ve passed, since recruiters value demonstrated progress toward the charter even before you complete it.' },
      { q: 'How long should a finance resume be?', a: 'One page for students, analysts, and most professionals; two pages only for senior roles with a long, relevant track record. Concise, precise formatting is itself a signal in finance.' }
    ],
    related: [relHub, { label: 'Financial Analyst resume example', href: '/resume-examples/financial-analyst' }, { label: 'How to pass the ATS', href: '/guides/how-to-pass-ats' }, { label: '150+ resume action verbs', href: '/guides/resume-action-verbs' }]
  },
  {
    slug: 'resume-builder-for-teachers', h1: 'Resume Builder for Teachers',
    title: 'Resume Builder for Teachers: Certified &amp; District-Ready',
    metaDescription: 'Free resume builder for teachers. Templates and examples built for K-12 educators to showcase certifications, endorsements, and measurable student outcomes.',
    answer: 'A teacher resume must lead with your state license, endorsements, and grade/subject expertise, then prove impact with measurable student outcomes. Districts screen for verified credentials and classroom results, so a teacher-specific resume builder helps you surface certifications and data that generic templates bury.',
    sections: [
      { h2: 'Why a teacher resume is different', bodyHtml: '&lt;p&gt;Unlike most private-sector resumes, a teacher resume is screened first for compliance: hiring principals and HR verify your state teaching license, endorsement areas, and the specific grade levels and subjects you\'re certified to teach before they read anything else. If your credentials aren\'t obvious in the top third, you can be filtered out regardless of experience.&lt;/p&gt;&lt;p&gt;Beyond credentials, districts want evidence of impact. They look for measurable student outcomes, classroom and behavior management, and command of curriculum standards and instructional methods. A strong teacher resume translates classroom work into data and demonstrated practice rather than a list of duties.&lt;/p&gt;' },
      { h2: 'What to put on a teacher resume', bodyHtml: '&lt;ul&gt;&lt;li&gt;&lt;strong&gt;State teaching license and endorsements&lt;/strong&gt; — list the state, certificate type, and endorsement areas (e.g., Elementary K-6, ELA 6-12, ESL, SPED); districts must verify you\'re legally cleared to teach the role.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Grade levels and subjects taught&lt;/strong&gt; — be specific (3rd grade, Algebra I, AP Biology) so hiring teams instantly see fit for the posted vacancy.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Measurable student outcomes&lt;/strong&gt; — proficiency or test-score gains, growth targets met, graduation or pass rates; this is the evidence principals use to compare candidates.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Classroom and behavior management&lt;/strong&gt; — approaches like PBIS or restorative practices show you can maintain a productive learning environment, a top district concern.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Curriculum and instructional methods&lt;/strong&gt; — standards alignment (Common Core, NGSS, state standards), differentiation, small-group instruction, and data-driven planning prove instructional skill.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;EdTech and classroom tools&lt;/strong&gt; — Google Classroom, Canvas, SMART Board, and assessment platforms signal you can teach in modern and blended settings.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Degrees and professional development&lt;/strong&gt; — your degree(s), National Board certification, and relevant PD or endorsements-in-progress show growth and qualification.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Student teaching and practicum&lt;/strong&gt; — new teachers should detail placement, grade, subject, and outcomes to substitute for full-time experience.&lt;/li&gt;&lt;/ul&gt;' },
      { h2: 'Teacher resume bullet examples', bodyHtml: '&lt;ul&gt;&lt;li&gt;Raised reading proficiency from &lt;strong&gt;62% to 84%&lt;/strong&gt; across two sections of 4th-grade ELA by implementing guided small-group instruction and biweekly running records.&lt;/li&gt;&lt;li&gt;Managed a diverse classroom of &lt;strong&gt;29 students&lt;/strong&gt;, including 6 with IEPs, using a PBIS framework that cut discipline referrals by &lt;strong&gt;40%&lt;/strong&gt; in one semester.&lt;/li&gt;&lt;li&gt;Designed targeted math interventions that moved &lt;strong&gt;18 of 22&lt;/strong&gt; below-grade students to on-level proficiency within a single academic year.&lt;/li&gt;&lt;/ul&gt;' }
    ],
    faq: [
      { q: 'How do I list my teaching certification on a resume?', a: 'Create a dedicated Certifications or Licensure section near the top. Include the issuing state, certificate type, endorsement areas, and expiration or renewal date, for example: "Texas Standard Certificate, EC-6 Generalist, ESL Supplemental (exp. 2027)." This lets HR verify eligibility fast.' },
      { q: 'What should a first-year teacher with no experience put on a resume?', a: 'Lead with your license (or licensure-in-progress) and degree, then detail student teaching: placement school, grade, subject, length, and any measurable results or lessons you designed. Add practicum hours, tutoring, coaching, and EdTech skills to show classroom readiness.' },
      { q: 'How long should a teacher resume be?', a: 'One page is standard for early-career teachers and most K-12 roles. Experienced educators, department chairs, or those with extensive PD and leadership can extend to two pages, but keep credentials and student outcomes on the first page where principals look first.' }
    ],
    related: [relHub, relExamples, { label: 'How to write a resume summary', href: '/guides/how-to-write-resume-summary' }, { label: 'How to pass the ATS', href: '/guides/how-to-pass-ats' }]
  },
  {
    slug: 'resume-builder-for-career-changers', h1: 'Resume Builder for Career Changers',
    title: 'Resume Builder for Career Changers: Switch Fields Fast',
    metaDescription: 'A resume builder for career changers that reframes transferable skills, leads with a target-role summary, and mirrors keywords from the jobs you actually want.',
    answer: 'A career-change resume works differently: instead of showcasing a linear history, it reframes your transferable skills for a field you haven\'t formally worked in. Lead with a summary naming your target role, translate past wins into the new field\'s language, and lean on a skills-forward format.',
    sections: [
      { h2: 'Why a career-change resume is different', bodyHtml: '&lt;p&gt;When you switch industries, recruiters can\'t map your history onto their org chart, so the burden is on you to connect the dots. The core challenge is reframing transferable skills for a field you haven\'t held a title in yet: your accomplishments are real, but they\'re written in the wrong vocabulary. Start with a strong summary that plainly states the target role, then translate each past achievement into the new field\'s language and keywords so a hiring manager sees relevance in seconds, not paragraphs.&lt;/p&gt;&lt;p&gt;Format matters here. A chronological layout foregrounds job titles that don\'t match the target, while a combination or skills-forward format lets you lead with capabilities and evidence before the job history that explains them.&lt;/p&gt;' },
      { h2: 'What to put on a career-change resume', bodyHtml: '&lt;ul&gt;&lt;li&gt;&lt;strong&gt;A targeted summary naming the new role&lt;/strong&gt; — tells recruiters in the first line you\'re applying &lt;em&gt;on purpose&lt;/em&gt;, not by accident.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Transferable skills mapped to the job description&lt;/strong&gt; — mirrors the exact requirements so both humans and ATS filters register a match.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Achievements reframed in the new field\'s terms&lt;/strong&gt; — "managed vendor budgets" becomes "controlled project spend," so wins read as relevant, not foreign.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Relevant certifications, courses, or bootcamps&lt;/strong&gt; — proves you\'ve invested in the switch and closed obvious knowledge gaps.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Side projects or volunteer work in the target field&lt;/strong&gt; — supplies real, in-domain evidence when your paid history can\'t.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Keywords pulled from actual target postings&lt;/strong&gt; — gets you past keyword screens and signals fluency in the field\'s terminology.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;A combination format when direct experience is thin&lt;/strong&gt; — puts skills and proof up top before the dates that reveal the pivot.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;De-emphasized unrelated detail&lt;/strong&gt; — trimming off-target jargon keeps the reader focused on why you fit the new role.&lt;/li&gt;&lt;/ul&gt;' },
      { h2: 'Career-change resume bullet examples', bodyHtml: '&lt;ul&gt;&lt;li&gt;Teacher to project manager: Coordinated schedules, materials, and stakeholders across &lt;strong&gt;6 concurrent programs&lt;/strong&gt;, delivering every one on time for two consecutive years.&lt;/li&gt;&lt;li&gt;Retail manager to data analyst: Built inventory dashboards in SQL and Excel that cut stockouts by &lt;strong&gt;30%&lt;/strong&gt; across a 12-store region.&lt;/li&gt;&lt;li&gt;Military logistics to supply chain: Directed distribution for &lt;strong&gt;$4M in equipment&lt;/strong&gt; with a 99% on-time accuracy rate under tight deadlines.&lt;/li&gt;&lt;/ul&gt;' }
    ],
    faq: [
      { q: 'Should a career changer use a functional or combination resume?', a: 'Use a combination format, not a purely functional one. It leads with a skills section that proves your fit, then still shows dated work history, which recruiters trust. Pure functional resumes often read as if you\'re hiding something and can confuse ATS parsing.' },
      { q: 'How do I explain my career change on the resume itself?', a: 'Handle it in the summary, not a long apology. In one or two lines, name your target role and connect your background to it, for example a professional bringing operations experience into a UX career. Save the fuller story for your cover letter and interviews.' },
      { q: 'Do I need new certifications to change careers?', a: 'Not always, but relevant certifications, courses, or bootcamps help when your paid experience doesn\'t cover the new field\'s core skills. They signal commitment and close obvious gaps. Pair them with side projects or volunteer work so you show applied ability, not just completion certificates.' }
    ],
    related: [relHub, { label: 'The best resume format', href: '/guides/best-resume-format' }, { label: 'How to tailor your resume to a job', href: '/guides/how-to-tailor-resume-to-job' }, relExamples]
  },
  {
    slug: 'resume-builder-for-no-experience', h1: 'Resume Builder for No Experience',
    title: 'Resume Builder for No Experience: First Resume Guide',
    metaDescription: 'Learn how to write a resume with no experience. Build a strong first resume from education, projects, volunteering, and transferable skills, plus real bullet examples.',
    answer: 'Everyone\'s first resume starts with zero work history, and that\'s completely normal. Build yours from what you do have: education, coursework, volunteering, personal or school projects, and transferable skills. A clear objective and a strong skills section do the heavy lifting, and one honest page is plenty.',
    sections: [
      { h2: 'How to write a resume with no experience', bodyHtml: '&lt;p&gt;Every professional you admire once had a blank resume, so start where you are. Instead of a work-history section, lead with a short objective naming the role you want, then let education, relevant coursework, volunteering, and personal or school projects show what you can do. Pull out transferable skills like communication, reliability, teamwork, and problem-solving, and back each one with a real example.&lt;/p&gt;&lt;p&gt;Keep it to one page, use clear headings, and never invent jobs or exaggerate titles. Employers hiring for entry-level roles expect a lighter resume; what they\'re really looking for is evidence you\'ll show up, learn fast, and follow through.&lt;/p&gt;' },
      { h2: 'What to put on a resume with no experience', bodyHtml: '&lt;ul&gt;&lt;li&gt;&lt;strong&gt;Contact info:&lt;/strong&gt; name, phone, professional email, and city so employers can reach you and see you\'re local.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;A short objective:&lt;/strong&gt; one or two lines naming the exact role and what you offer, giving your resume focus from the first glance.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Education:&lt;/strong&gt; school, program, expected or completed graduation, and GPA if it\'s strong, since it\'s often your biggest credential.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Relevant coursework:&lt;/strong&gt; classes tied to the job that prove you already have foundational knowledge.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Volunteer work and informal jobs:&lt;/strong&gt; babysitting, tutoring, yard work, church or community help, all of which show responsibility and real effort.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Personal or school projects:&lt;/strong&gt; anything you built, organized, or led, demonstrating initiative and hands-on skill.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Transferable and soft skills:&lt;/strong&gt; teamwork, dependability, and communication with a quick example, because these are what entry-level managers screen for.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Certifications, online courses, and honors:&lt;/strong&gt; proof you take initiative to learn and were recognized for it.&lt;/li&gt;&lt;/ul&gt;' },
      { h2: 'No-experience resume bullet examples', bodyHtml: '&lt;ul&gt;&lt;li&gt;Tutored &lt;strong&gt;5&lt;/strong&gt; middle-school students weekly in math, helping each raise their quiz scores over one semester.&lt;/li&gt;&lt;li&gt;Organized a school fundraiser that sold tickets to more than &lt;strong&gt;200&lt;/strong&gt; attendees and exceeded the class goal.&lt;/li&gt;&lt;li&gt;Managed regular babysitting for &lt;strong&gt;3&lt;/strong&gt; children, coordinating meals, homework, and schedules for working parents.&lt;/li&gt;&lt;/ul&gt;' }
    ],
    faq: [
      { q: 'Can I write a resume if I\'ve never had a job?', a: 'Yes. Focus on education, coursework, volunteering, personal or school projects, and informal work like babysitting or tutoring. These show responsibility and skills even without a formal job title.' },
      { q: 'How long should a resume with no experience be?', a: 'One page. With no work history you won\'t need more, and a clean, focused single page is easier for employers to scan than a padded one.' },
      { q: 'What skills should I list with no experience?', a: 'Transferable and soft skills such as communication, teamwork, reliability, time management, and problem-solving. Back each with a short, real example from school, volunteering, or home so it\'s believable.' }
    ],
    related: [relHub, { label: 'How to write a resume summary', href: '/guides/how-to-write-resume-summary' }, { label: 'How to list skills on a resume', href: '/guides/how-to-list-skills-on-a-resume' }, relExamples]
  },
  {
    slug: 'resume-builder-for-project-managers', h1: 'Resume Builder for Project Managers',
    title: 'Resume Builder for Project Managers | PM Resume Tips',
    metaDescription: 'Free resume builder for project managers. Get PM-specific bullet examples, certifications (PMP, CSM), and quantified templates recruiters actually scan for.',
    answer: 'A resume builder for project managers helps you frame delivery, not duties. PM resumes win when every bullet ties to scope, budget, timeline, and outcomes, and when certifications like PMP or CSM, methodologies, and tools are easy to scan in seconds.',
    sections: [
      { h2: 'Why a project manager resume is different', bodyHtml: '&lt;p&gt;Unlike most roles, a PM resume is judged on how you deliver work through others: recruiters scan for the scope you owned (budget, team size, timeline), the outcomes you drove, and proof you can run a plan under pressure. Vague bullets like "managed projects" tell them nothing.&lt;/p&gt;&lt;p&gt;Applicant tracking systems and hiring managers both look for signals fast: certifications (PMP, CSM, PMI-ACP), methodologies (Agile, Scrum, Waterfall), and tools (Jira, MS Project, Asana). If those aren\'t obvious in the top third of the page, strong PMs get filtered out. Every bullet should quantify budget, time, or team.&lt;/p&gt;' },
      { h2: 'What to put on a project manager resume', bodyHtml: '&lt;ul&gt;&lt;li&gt;&lt;strong&gt;Certifications (PMP, CSM, PMI-ACP):&lt;/strong&gt; these are hard filters for many PM reqs, so list them near your name or summary where a recruiter sees them first.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Methodologies (Agile, Scrum, Waterfall):&lt;/strong&gt; naming your delivery approach signals fit for how the team actually works.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Tools (Jira, MS Project, Asana, Confluence):&lt;/strong&gt; match the job posting\'s stack so you clear ATS keyword screens.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Quantified project scope (budget, team size, timeline):&lt;/strong&gt; numbers show the level you operate at far better than a title.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Delivery outcomes (on-time / under-budget %):&lt;/strong&gt; hiring managers care most about results, not activity.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Stakeholder management:&lt;/strong&gt; proof you align sponsors, vendors, and cross-functional teams sets senior PMs apart.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Risk and issue management:&lt;/strong&gt; shows you anticipate problems instead of just reporting them.&lt;/li&gt;&lt;li&gt;&lt;strong&gt;A metrics-heavy summary:&lt;/strong&gt; three lines up top with your biggest numbers frame everything a recruiter reads next.&lt;/li&gt;&lt;/ul&gt;' },
      { h2: 'Project manager resume bullet examples', bodyHtml: '&lt;ul&gt;&lt;li&gt;Delivered a &lt;strong&gt;$4.2M&lt;/strong&gt; ERP implementation &lt;strong&gt;3 weeks ahead of schedule&lt;/strong&gt; by re-sequencing critical-path tasks across 4 vendor teams.&lt;/li&gt;&lt;li&gt;Led a cross-functional team of &lt;strong&gt;18&lt;/strong&gt; to ship 12 releases with a &lt;strong&gt;96% on-time delivery&lt;/strong&gt; rate over 2 years.&lt;/li&gt;&lt;li&gt;Cut project spend &lt;strong&gt;$310K (14%)&lt;/strong&gt; by renegotiating vendor scope and eliminating duplicate tooling.&lt;/li&gt;&lt;/ul&gt;' }
    ],
    faq: [
      { q: 'Should I put my PMP or CSM certification at the top of my resume?', a: 'Yes. Because many PM job reqs treat PMP, CSM, or PMI-ACP as hard requirements, list credentials next to your name or in your summary so a recruiter sees them in the first few seconds instead of hunting at the bottom.' },
      { q: 'How do I quantify project management work if my results were confidential?', a: 'Use ranges, percentages, or relative figures instead of exact dollar amounts, for example "managed a mid-seven-figure budget" or "reduced cycle time 20%." These still prove scope and impact without disclosing sensitive numbers.' },
      { q: 'How long should a project manager resume be?', a: 'One page for under 10 years of experience, two pages for senior or program-level PMs. Prioritize recent, high-scope projects with quantified outcomes and trim older roles to a line or two.' }
    ],
    related: [relHub, { label: 'How to tailor your resume to a job', href: '/guides/how-to-tailor-resume-to-job' }, { label: 'How to pass the ATS', href: '/guides/how-to-pass-ats' }, relExamples]
  }
];

// Write hub
fs.writeFileSync(path.join(ROOT, hub.slug + '.html'), page(hub));
// Write audience pages (with the shared Resume Builder breadcrumb parent)
audiences.forEach(a => {
  a.crumbNav = RB_PARENT_NAV;
  a.crumbParent = RB_PARENT_LD;
  a.finalTitle = 'Build your ' + a.h1.replace(/^Resume Builder for /, '').toLowerCase() + ' resume free';
  fs.writeFileSync(path.join(ROOT, a.slug + '.html'), page(a));
});

console.log('Generated:', [hub.slug].concat(audiences.map(a => a.slug)).join(', '));
